version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Evita conflictos de volúmenes con dependencias
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=my_database
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
